alias l="ls -1"
#alias ack="ack-grep --ignore-dir=node_modules --ignore-dir=vendor --ignore-dir=bower_components"
alias c.="cd .."
alias c.l="cd .. ; ls -1"
alias tmux="TERM=screen-256color-bce tmux"
